name: credit_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #UI DESIGN
  cupertino_icons: ^1.0.2
  font_awesome_flutter: 9.2.0
  dotted_border: 2.0.0+2
  carousel_slider: 4.0.0
  introduction_screen: 2.1.0
  scratcher: 2.1.0
  material_design_icons_flutter: 5.0.6595
  convex_bottom_bar: 3.0.0
  
  #STATE MANAGEMENT
  get: ^4.6.1

  #LOCAL 
  get_storage: 2.0.3

  #IMAGE
  image_picker: 0.8.4+3
  flutter_image_compress: 1.1.0
  image_cropper: 1.4.1

  #OTHERS
  intl: 0.17.0
  provider: any
  flutter_svg: 1.0.3
  pinput: 1.2.2
  page_view_indicators: 2.0.0
  date_format: 2.0.4
  permission_handler: ^8.3.0
  dots_indicator: ^2.1.0
  firebase_core: ^2.6.1
  firebase_storage: ^11.0.13
  firebase_auth: ^4.2.8
  cloud_firestore: ^4.4.2
  fluttertoast: ^8.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf

